---
- name: create a VPC with dedicated tenancy and a couple of tags
  ec2_vpc_net:
    name: "{{name}}"
    cidr_block: "{{cidr_block}}"
    region: "{{region}}"
    dns_hostnames: yes
    dns_support: yes
    multi_ok: no
    tenancy: default
    state: present
  register: vpc

- name: Associating an igw to vpc
  ec2_vpc_igw:
    region: "{{region}}"
    vpc_id: "{{ vpc.vpc.id }}"
    tags:
      Name: "{{name}}"
    state: present
  register: igw

- name: associate subnet to VPC
  ec2_vpc_subnet:
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ region }}"
    cidr: "{{ item.cidr }}"
    az: "{{ item.az }}"
    map_public: yes
    resource_tags:
      Name: "{{ item.name }}"
    state: present
  register: subnet
  loop:
    - { name: Subnet A, az: "{{ region }}a", cidr: "{{ cidr_subnet_a }}" }
    - { name: Subnet B, az: "{{ region }}b", cidr: "{{ cidr_subnet_b }}" }
    - { name: Subnet C, az: "{{ region }}c", cidr: "{{ cidr_subnet_c }}" }
  register: vpc_subnet

