---
- name: Gather information about the VPC with the provided name
  ec2_vpc_net_info:
    filters:
      "tag:Name": "{{name}}"
  register: vpc_info

- name: Delete the associate igw
  ec2_vpc_igw:
    vpc_id: "{{vpc_info.vpcs[0].vpc_id}}"
    state: absent
  register: igw

- name: delete the VPC
  ec2_vpc_net:
    name: "{{name}}"
    cidr_block: "{{cidr_block}}"
    region: "{{region}}"
    dns_hostnames: yes
    dns_support: yes
    multi_ok: no
    tenancy: default
    state: absent
  register: vpc