---
- name: Gather information about the VPC with the provided name
  ec2_vpc_net_info:
    region: "{{region}}"
    filters:
      "tag:Name": "{{name}}"
  register: vpc_info

- name: associate subnet to VPC
  ec2_vpc_subnet:
    vpc_id: "{{vpc_info.vpcs[0].vpc_id}}"
    cidr: "{{ item.cidr }}"
    region: "{{ region }}"
    resource_tags:
      Name: "{{ item.name }}"
    state: absent
  register: subnet
  loop:
    - { name: Subnet A, cidr: "{{ cidr_subnet_a }}" }
    - { name: Subnet B, cidr: "{{ cidr_subnet_b }}" }
    - { name: Subnet C, cidr: "{{ cidr_subnet_c }}" }
  register: vpc_subnet

- name: Delete the associate igw
  ec2_vpc_igw:
    region: "{{region}}"
    vpc_id: "{{vpc_info.vpcs[0].vpc_id}}"
    state: absent
  register: igw

- name: delete the VPC
  ec2_vpc_net:
    region: "{{region}}"
    name: "{{name}}"
    cidr_block: "{{cidr_block}}"
    purge_cidrs: yes  
    state: absent
  register: vpc