---
- name: Provision instances
  ec2_instance:
    name: "public-compute-instance"
    region: "{{ ec2_region }}"
    instance_type: "{{ ec2_instance_type }}"
    security_group: "{{ ec2_security_group }}"
    image_id: "{{ ec2_image }}"
    key_name: "{{ ec2_keypair }}"
  register: ec2

# - name: Wait for SSH to come up
#   wait_for:
#     host: "{{ item.public_dns_name }}"
#     port: 22
#     delay: 60
#     timeout: 320
#     state: started
#   with_items: "{{ ec2.instances }}"
