---
- name: example using security group rule descriptions
  ec2_group:
    name: "sgansibletest"
    description: sg with rule descriptions
    vpc_id: vpc-0180626a
    region: us-east-2
    rules:
      - proto: tcp
        ports:
        - 80
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all on port 80

# - name: Get the full list of method parameters (get_method_parameters)
#   manageiq_automate:
#     workspace: "{{ workspace }}"
#     get_method_parameters: yes
#   register: get_method_parameters

- name: Provision instances
  ec2_instance:
    name: "public-compute-instance"
    region: "{{ ec2_region }}"
    instance_type: t2.micro
    security_group: "{{ ec2_security_group }}"
    image_id: "{{ ec2_image }}"
    key_name: "{{ ec2_keypair }}"
  register: ec2

# - name: Wait for SSH to come up
#   wait_for:
#     host: "{{ item.public_dns_name }}"
#     port: 22
#     delay: 60
#     timeout: 320
#     state: started
#   with_items: "{{ ec2.instances }}"
