---
- name: Get the full list of method parameters (get_method_parameters)
  manageiq_automate:
    workspace: "{{ workspace }}"
    get_method_parameters: yes
  register: get_method_parameters

- name: Provision instances
  ec2_instance:
    name: "public-compute-instance"
    region: "{{ get_method_parameters.ec2_region }}"
    instance_type: "{{ get_method_parameters.ec2_instance_type }}"
    security_group: "{{ get_method_parameters.ec2_security_group }}"
    image_id: "{{ get_method_parameters.ec2_image }}"
    key_name: "{{ get_method_parameters.ec2_keypair }}"
  register: ec2

# - name: Wait for SSH to come up
#   wait_for:
#     host: "{{ item.public_dns_name }}"
#     port: 22
#     delay: 60
#     timeout: 320
#     state: started
#   with_items: "{{ ec2.instances }}"
