---

# - name: Get the full list of method parameters (get_method_parameters)
#   manageiq_automate:
#     workspace: "{{ workspace }}"
#     get_method_parameters: yes
#   register: get_method_parameters

# - name: Debug
#   debug: 
#     msg: get_method_parameters

- name: Delete a s3 bucket
  s3_bucket:
    region: "{{region}}"
    name: "{{name}}"
    state: absent
    force: yes